### ISSUE TITLE
Safari <= 13 support

### ISSUE THREAD

**Issue by egorprnn** [852Kerfunkle/threads-es#5]
`EventTarget` class does not support `extends` feature on safari <= 13 and this causes an error:

![Снимок экрана 2023-11-07 в 17 54 25](https://github.com/852Kerfunkle/threads-es/assets/42776347/341a804c-e9f7-4c36-b377-10823697ec42)

https://github.com/852Kerfunkle/threads-es/blob/49502c62d6f2ba028895edcb7ba6efcbdab8e499/src/controller/thread/EsThread.ts#L58

https://github.com/852Kerfunkle/threads-es/blob/49502c62d6f2ba028895edcb7ba6efcbdab8e499/src/controller/pool/EsThreadPool.ts#L45

https://stackoverflow.com/a/58209729

**Comment by 852Kerfunkle** [comment]
Good day Egor. Thank you for letting me know about this issue.

Not to be "that guy", but High Sierra isn't officially supported anymore,
presumably the number of users on safari <= 13 wouldn't be that high.

Regardless of that - also maybe because sometimes the only way to update
your Mac or iPhone OS is to buy a new device, and I'm no fan of that - I'll
have a look if can resolve this in a way that's not too terrible.

Genrally, I was targeting modern browsers, but what can you do... :)

**Comment by 852Kerfunkle** [comment]
@MrZillaGold Didn't quite intend to close the issue with the commit.

Please give v0.3.4 a try and if the issue should persist on Safari 13, reopen the issue.

Thanks!
